"""add_is_anomaly_to_sensor_readings

Revision ID: 12dbb393bbb6
Revises: f4b35149657d
Create Date: 2026-05-31 21:39:58.340227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12dbb393bbb6'
down_revision: Union[str, None] = 'f4b35149657d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_readings', sa.Column('is_anomaly', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor_readings', 'is_anomaly')
    # ### end Alembic commands ###
