"""initial_schema

Revision ID: f4b35149657d
Revises: 
Create Date: 2026-05-31 12:50:34.149923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4b35149657d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('floor_count', sa.Integer(), nullable=True),
    sa.Column('installed_date', sa.String(), nullable=False),
    sa.Column('reading_types', sa.JSON(), nullable=False),
    sa.Column('alert_thresholds', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('ix_users_token', 'users', ['token'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('reading_value', sa.Float(), nullable=True),
    sa.Column('reading_name', sa.String(), nullable=True),
    sa.Column('timestamp_utc', sa.BigInteger(), nullable=False),
    sa.Column('timestamp_local', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('acknowledged_at', sa.BigInteger(), nullable=True),
    sa.Column('resolved_at', sa.BigInteger(), nullable=True),
    sa.Column('resolution_type', sa.String(), nullable=True),
    sa.Column('resolution_root_cause', sa.String(), nullable=True),
    sa.Column('resolution_action_taken', sa.String(), nullable=True),
    sa.Column('resolution_preventive_measures', sa.String(), nullable=True),
    sa.Column('resolution_time_spent_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_device_id', 'alerts', ['device_id'], unique=False)
    op.create_index('ix_alerts_severity', 'alerts', ['severity'], unique=False)
    op.create_index('ix_alerts_status', 'alerts', ['status'], unique=False)
    op.create_table('recoveries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('timestamp_utc', sa.BigInteger(), nullable=False),
    sa.Column('reading_value', sa.Float(), nullable=True),
    sa.Column('reading_name', sa.String(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('timestamp_utc', sa.BigInteger(), nullable=False),
    sa.Column('reading_name', sa.String(), nullable=False),
    sa.Column('reading_value', sa.Float(), nullable=False),
    sa.Column('breaches_threshold', sa.Boolean(), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sensor_readings_device_id_timestamp_utc', 'sensor_readings', ['device_id', 'timestamp_utc'], unique=False)
    op.create_table('alert_timeline',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_timeline_alert_id_timestamp', 'alert_timeline', ['alert_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alert_timeline_alert_id_timestamp', table_name='alert_timeline')
    op.drop_table('alert_timeline')
    op.drop_index('ix_sensor_readings_device_id_timestamp_utc', table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_table('recoveries')
    op.drop_index('ix_alerts_status', table_name='alerts')
    op.drop_index('ix_alerts_severity', table_name='alerts')
    op.drop_index('ix_alerts_device_id', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_users_token', table_name='users')
    op.drop_table('users')
    op.drop_table('devices')
    # ### end Alembic commands ###
